POST http://127.0.0.1:8000/api/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/api/test-token 
Content-Type: application/json
Authorization: Token 8885da491e449a24b04f7c2167c7657c75748f97